/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Module } from '@nestjs/common';
import { DI } from '@/di-symbols.js';
import {
	MiAbuseNoteAutoCheck,
	MiAbuseReportNotificationRecipient,
	MiAbuseUserReport,
	MiAccessToken,
	MiAd,
	MiAnnouncement,
	MiAnnouncementRead,
	MiAntenna,
	MiApp,
	MiAuthSession,
	MiAvatarDecoration,
	MiBlocking,
	MiBubbleGameRecord,
	MiChannel,
	MiChannelFavorite,
	MiChannelFollowing,
	MiClip,
	MiClipFavorite,
	MiClipNote,
	MiDriveFile,
	MiDriveFolder,
	MiEmailTemplates,
	MiEmoji,
	MiFlash,
	MiFlashLike,
	MiFollowing,
	MiFollowRequest,
	MiGalleryLike,
	MiGalleryPost,
	MiHashtag,
	MiInstance,
	MiMeta,
	MiModerationLog,
	MiMuting,
	MiNote,
	MiNoteFavorite,
	MiNoteReaction,
	MiNoteThreadMuting,
	MiNoteDraft,
	MiPage,
	MiPageLike,
	MiPasswordResetRequest,
	MiPoll,
	MiPollVote,
	MiPromoNote,
	MiPromoRead,
	MiRegistrationTicket,
	MiRegistryItem,
	MiRelay,
	MiRenoteMuting,
	MiRepository,
	miRepository,
	MiRetentionAggregation,
	MiReversiGame,
	MiRole,
	MiRoleAssignment,
	MiSignin,
	MiSwSubscription,
	MiSystemAccount,
	MiSystemWebhook,
	MiUsedUsername,
	MiUser,
	MiUserIp,
	MiUserKeypair,
	MiUserList,
	MiUserListFavorite,
	MiUserListMembership,
	MiUserMemo,
	MiUserNotePining,
	MiUserPending,
	MiUserProfile,
	MiUserPublickey,
	MiUserSecurityKey,
	MiWebhook,
	MiChatMessage,
	MiChatRoom,
	MiChatRoomMembership,
	MiChatRoomInvitation,
	MiChatApproval,
	MiUserSessions,
	MiUserRiskScoreHistory,
	MiRiskEventLog,
	MiUserMultiAccountLink,
	MiUserRecommendationProfile,
	MiContentRecommendationLog,
	MiUserInteractionHistory,
	MiContentEmbedding,
	MiUserInterestEmbedding,
	MiEmbeddingBatchQueue,
	MiStripeCustomer,
	MiStripePayment,
	MiStripeSubscription,
	MiStripeRefund,
} from './_.js';
import type { Provider } from '@nestjs/common';
import type { DataSource, EntityTarget } from 'typeorm';

function createRepositoryProvider(token: symbol, entity: EntityTarget<any>): Provider {
	return {
		provide: token,
		useFactory: (db: DataSource) => db.getRepository(entity as any).extend(miRepository),
		inject: [DI.db],
	};
}

const repositoryMappings = [
	{ token: DI.usersRepository, entity: MiUser },
	{ token: DI.notesRepository, entity: MiNote },
	{ token: DI.announcementsRepository, entity: MiAnnouncement },
	{ token: DI.announcementReadsRepository, entity: MiAnnouncementRead },
	{ token: DI.appsRepository, entity: MiApp },
	{ token: DI.avatarDecorationsRepository, entity: MiAvatarDecoration },
	{ token: DI.noteFavoritesRepository, entity: MiNoteFavorite },
	{ token: DI.noteThreadMutingsRepository, entity: MiNoteThreadMuting },
	{ token: DI.noteReactionsRepository, entity: MiNoteReaction },
	{ token: DI.noteDraftsRepository, entity: MiNoteDraft },
	{ token: DI.pollsRepository, entity: MiPoll },
	{ token: DI.pollVotesRepository, entity: MiPollVote },
	{ token: DI.userProfilesRepository, entity: MiUserProfile },
	{ token: DI.userKeypairsRepository, entity: MiUserKeypair },
	{ token: DI.userPendingsRepository, entity: MiUserPending },
	{ token: DI.userSecurityKeysRepository, entity: MiUserSecurityKey },
	{ token: DI.userPublickeysRepository, entity: MiUserPublickey },
	{ token: DI.userListsRepository, entity: MiUserList },
	{ token: DI.userListFavoritesRepository, entity: MiUserListFavorite },
	{ token: DI.userListMembershipsRepository, entity: MiUserListMembership },
	{ token: DI.userNotePiningsRepository, entity: MiUserNotePining },
	{ token: DI.userIpsRepository, entity: MiUserIp },
	{ token: DI.usedUsernamesRepository, entity: MiUsedUsername },
	{ token: DI.followingsRepository, entity: MiFollowing },
	{ token: DI.followRequestsRepository, entity: MiFollowRequest },
	{ token: DI.instancesRepository, entity: MiInstance },
	{ token: DI.emailTemplatesRepository, entity: MiEmailTemplates },
	{ token: DI.emojisRepository, entity: MiEmoji },
	{ token: DI.driveFilesRepository, entity: MiDriveFile },
	{ token: DI.driveFoldersRepository, entity: MiDriveFolder },
	{ token: DI.metasRepository, entity: MiMeta },
	{ token: DI.mutingsRepository, entity: MiMuting },
	{ token: DI.renoteMutingsRepository, entity: MiRenoteMuting },
	{ token: DI.blockingsRepository, entity: MiBlocking },
	{ token: DI.swSubscriptionsRepository, entity: MiSwSubscription },
	{ token: DI.systemAccountsRepository, entity: MiSystemAccount },
	{ token: DI.hashtagsRepository, entity: MiHashtag },
	{ token: DI.abuseNoteAutoCheckRepository, entity: MiAbuseNoteAutoCheck },
	{ token: DI.abuseUserReportsRepository, entity: MiAbuseUserReport },
	{ token: DI.abuseReportNotificationRecipientRepository, entity: MiAbuseReportNotificationRecipient },
	{ token: DI.registrationTicketsRepository, entity: MiRegistrationTicket },
	{ token: DI.authSessionsRepository, entity: MiAuthSession },
	{ token: DI.accessTokensRepository, entity: MiAccessToken },
	{ token: DI.signinsRepository, entity: MiSignin },
	{ token: DI.pagesRepository, entity: MiPage },
	{ token: DI.pageLikesRepository, entity: MiPageLike },
	{ token: DI.galleryPostsRepository, entity: MiGalleryPost },
	{ token: DI.galleryLikesRepository, entity: MiGalleryLike },
	{ token: DI.moderationLogsRepository, entity: MiModerationLog },
	{ token: DI.clipsRepository, entity: MiClip },
	{ token: DI.clipNotesRepository, entity: MiClipNote },
	{ token: DI.clipFavoritesRepository, entity: MiClipFavorite },
	{ token: DI.antennasRepository, entity: MiAntenna },
	{ token: DI.promoNotesRepository, entity: MiPromoNote },
	{ token: DI.promoReadsRepository, entity: MiPromoRead },
	{ token: DI.relaysRepository, entity: MiRelay },
	{ token: DI.channelsRepository, entity: MiChannel },
	{ token: DI.channelFollowingsRepository, entity: MiChannelFollowing },
	{ token: DI.channelFavoritesRepository, entity: MiChannelFavorite },
	{ token: DI.registryItemsRepository, entity: MiRegistryItem },
	{ token: DI.webhooksRepository, entity: MiWebhook },
	{ token: DI.systemWebhooksRepository, entity: MiSystemWebhook },
	{ token: DI.adsRepository, entity: MiAd },
	{ token: DI.passwordResetRequestsRepository, entity: MiPasswordResetRequest },
	{ token: DI.retentionAggregationsRepository, entity: MiRetentionAggregation },
	{ token: DI.flashsRepository, entity: MiFlash },
	{ token: DI.flashLikesRepository, entity: MiFlashLike },
	{ token: DI.rolesRepository, entity: MiRole },
	{ token: DI.roleAssignmentsRepository, entity: MiRoleAssignment },
	{ token: DI.userMemosRepository, entity: MiUserMemo },
	{ token: DI.chatMessagesRepository, entity: MiChatMessage },
	{ token: DI.chatRoomsRepository, entity: MiChatRoom },
	{ token: DI.chatRoomMembershipsRepository, entity: MiChatRoomMembership },
	{ token: DI.chatRoomInvitationsRepository, entity: MiChatRoomInvitation },
	{ token: DI.chatApprovalsRepository, entity: MiChatApproval },
	{ token: DI.bubbleGameRecordsRepository, entity: MiBubbleGameRecord },
	{ token: DI.reversiGamesRepository, entity: MiReversiGame },
	{ token: DI.userSessionsRepository, entity: MiUserSessions },
	{ token: DI.userRiskScoreHistoryRepository, entity: MiUserRiskScoreHistory },
	{ token: DI.riskEventLogRepository, entity: MiRiskEventLog },
	{ token: DI.userMultiAccountLinkRepository, entity: MiUserMultiAccountLink },
	{ token: DI.userRecommendationProfileRepository, entity: MiUserRecommendationProfile },
	{ token: DI.contentRecommendationLogRepository, entity: MiContentRecommendationLog },
	{ token: DI.userInteractionHistoryRepository, entity: MiUserInteractionHistory },
	{ token: DI.contentEmbeddingRepository, entity: MiContentEmbedding },
	{ token: DI.userInterestEmbeddingRepository, entity: MiUserInterestEmbedding },
	{ token: DI.embeddingBatchQueueRepository, entity: MiEmbeddingBatchQueue },
	{ token: DI.stripeCustomersRepository, entity: MiStripeCustomer },
	{ token: DI.stripePaymentsRepository, entity: MiStripePayment },
	{ token: DI.stripeSubscriptionsRepository, entity: MiStripeSubscription },
	{ token: DI.stripeRefundsRepository, entity: MiStripeRefund },
] as const;

const providers = repositoryMappings.map(({ token, entity }) =>
	createRepositoryProvider(token, entity)
);

@Module({
	imports: [],
	providers,
	exports: providers,
})
export class RepositoryModule {
}
