/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class GeocodingIndex {
  constructor()
  add(index: number, lat: number, lon: number, importance: number): void
  search(lat: number, lon: number, radiusKm: number, limit: number): number[]
}

export function normalizeForSearch(text: string): string
export function safeForSql(text: string): boolean
export function generateIdenticon(seed: string): Buffer
export function htmlToMfm(html: string, hashtagNames?: Array<string> | undefined | null): string
